### PR TITLE
Update for node 12 (wip)

### PR DESCRIPTION
**Pull request by lmeyerov**
Updates `node-opencl` for node 12.11 / nan 2.10:

Blockers
- [x] Compiles with no errors
- [ ] Tested on production workloads

Nice-to-have 
- [ ] Many build warnings:  https://pastebin.com/vxvzfKah
- [ ] Test failures, unclear if new: https://pastebin.com/HXS16REs

Overall changes:
-- Garden: separate out dev deps (speed + work around memwatch), update packagelock
-- Nan updates <-- worth checking https://github.com/mikeseven/node-opencl/pull/71/commits/c3b201a95874059393e7b5d7ac287fc3be067b37, I called out the basic forms repeated in it in the comments
-- Disable memwatch tests as memwatch does not build
-- Update gc flag

Will test on-and-off. Only have intel + nvidia hw for testing, w/ nvidia being our primary goal.

Happy to help get upstream, though limited bandwidth. Maybe package as `node-opencl-next` in the meanwhile.

### CODE REVIEW

**Comment by lmeyerov** [comment]
cc @mikeseven Let me know how you'd like this to be handled

**Comment by lmeyerov** [comment]
Ah, just saw https://github.com/trxcllnt/node-opencl/pull/1 ... looking.

**Comment by lmeyerov** [comment]
Yeah, created combined branch w/ latest updates from @lu4 / @trxcllnt  => https://github.com/graphistry/node-opencl#next .

**Comment by trxcllnt** [comment]
https://github.com/mikeseven/node-opencl/pull/69

**Comment by lmeyerov** [comment]
100%, redid https://github.com/graphistry/node-opencl/commits/next to add the next 2 @lu4 commits + dug into one of the failing tests.. will close this and refile

**Comment by lmeyerov** [comment]
Moved to https://github.com/mikeseven/node-opencl/pull/69 as  https://github.com/trxcllnt/node-opencl/pull/3

**Pull request closed without merging**
